# Generated by Django 4.1.7 on 2023-06-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0002_titleproduct_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
