# Generated by Django 4.1.7 on 2023-05-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0002_alter_company_company_alter_company_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=100, verbose_name='Наименование изделия')),
                ('type_product', models.CharField(max_length=50, verbose_name='Тип изделия')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vappiter.company', verbose_name='Производитель')),
            ],
        ),
    ]
