# Generated by Django 4.2 on 2023-05-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nameproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduct', models.CharField(max_length=100, verbose_name='Наименование изделия')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.company', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(max_length=50, verbose_name='Модель изделия'),
        ),
        migrations.AddField(
            model_name='product',
            name='nameproduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.nameproduct', verbose_name='Наименование изделия'),
        ),
    ]
