# Generated by Django 4.1.7 on 2023-05-31 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0004_nameproduct_remove_product_title_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=4, verbose_name='Блок')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=25, verbose_name='Здание')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=5, verbose_name='Этаж')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10, verbose_name='Этаж')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sernum', models.CharField(max_length=20, verbose_name='Серийный номер')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.block', verbose_name='Блок')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.building', verbose_name='Здание')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.level', verbose_name='Уровень')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.room', verbose_name='Помещение')),
                ('type_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.product', verbose_name='Модель изделия')),
            ],
        ),
    ]
