# Generated by Django 4.1.7 on 2023-05-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0005_block_building_level_room_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='building',
            new_name='level',
        ),
    ]
