# Generated by Django 4.1.7 on 2023-06-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Модель изделия')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.company', verbose_name='Производитель')),
                ('titleproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.titleproduct', verbose_name='Наименование изделия')),
            ],
        ),
    ]
