# Generated by Django 4.1.7 on 2023-06-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0007_block_building_level_room_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sernum', models.CharField(max_length=20, null=True, verbose_name='Серийный номер')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.block', verbose_name='Блок')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.building', verbose_name='Здание')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.level', verbose_name='Уровень')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.room', verbose_name='Помещение')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.system', verbose_name='Система КИТСО')),
                ('type_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.product', verbose_name='Модель изделия')),
            ],
        ),
    ]
