# Generated by Django 4.1.7 on 2023-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0008_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='fullnamesystem',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование системы'),
        ),
    ]
