# Generated by Django 4.1.7 on 2023-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0009_alter_system_fullnamesystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='fullnamesystem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование системы'),
        ),
    ]
