# Generated by Django 4.1.7 on 2023-06-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0010_alter_system_fullnamesystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.block', verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.room', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sernum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.system', verbose_name='Система КИТСО'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vappiter.product', verbose_name='Модель изделия'),
        ),
    ]
