# Generated by Django 4.1.7 on 2023-06-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vappiter', '0011_alter_equipment_block_alter_equipment_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='type_product',
            new_name='product',
        ),
    ]
