# Generated by Django 4.1.7 on 2023-06-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_equipment', '0003_box_alter_room_room_equipment_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='sernum',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Серийный номер'),
        ),
    ]
