# Generated by Django 4.1.7 on 2023-06-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_equipment', '0004_alter_equipment_sernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block',
            field=models.CharField(max_length=13, verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=13, verbose_name='Помещение'),
        ),
    ]
